# Generated by Django 4.1.3 on 2022-11-05 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0002_category_user_transaction_user_defaultcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deal.defaultcategory'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='deal.category'),
        ),
    ]
