# Generated by Django 4.1.3 on 2022-11-05 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0003_alter_category_cat_name_alter_transaction_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defaultcategory',
            old_name='def_cat',
            new_name='cat_name',
        ),
    ]
