# Generated by Django 4.1.3 on 2022-11-05 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0005_alter_transaction_category_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultcategory',
            name='cat_name',
            field=models.CharField(choices=[('Забота о себе', 'Забота о себе'), ('Зарплата', 'Зарплата'), ('Здоровье и фитнес', 'Здоровье и фитнес'), ('Кафе и рестораны', 'Кафе и рестораны'), ('Машина', 'Машина'), ('Образование', 'Образование'), ('Отдых и развлечения', 'Отдых и развлечения'), ('Платежи, комиссии', 'Платежи, комиссии'), ('Покупки: одежда, техника', 'Покупки: одежда, техника'), ('Продукты', 'Продукты'), ('Проезд', 'Проезд'), ('Своя категория', 'Своя категория')], max_length=255),
        ),
    ]
