# Generated by Django 4.1.3 on 2022-11-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0006_alter_defaultcategory_cat_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
