# Generated by Django 4.1.3 on 2022-11-07 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0007_transaction_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='amount',
        ),
    ]
