# Generated by Django 4.1.3 on 2022-11-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0009_transaction_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='balance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
