# Generated by Django 4.1.3 on 2022-11-07 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0010_alter_transaction_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='user',
            new_name='username',
        ),
    ]
