# Generated by Django 4.1.3 on 2022-11-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0011_rename_user_transaction_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='balance',
        ),
        migrations.AddField(
            model_name='transaction',
            name='user_balance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
