# Generated by Django 4.1.3 on 2022-11-08 00:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0012_remove_transaction_balance_transaction_user_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 8, 3, 0, 34, 444968)),
        ),
    ]
